name: PR Build

on: [pull_request]

jobs:
  build:
    name: Build iOS app
    permissions:
      contents: read
    uses: VeamStudios/.github/.github/workflows/pr-ios-build.yml@main
    with:
      xcode_version: "26.2"
      xcodebuild_args: '-project "Site Audit Pro.xcodeproj" -scheme Dev CODE_SIGN_IDENTITY="" CODE_SIGN_ALLOWED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_REQUIRED=NO'
    secrets: inherit
