name: Deploy Dev

on:
  workflow_dispatch:

concurrency:
  group: deploy-dev-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      deployment_environment: dev
      build_script: build-dev
      firebase_project: site-audit-pro-dev
      service_account_file: sa-dev.json
      firebase_config_file: firebase-dev-beta.json
    secrets:
      SERVICE_ACCOUNT_BASE64: ${{ secrets.SERVICE_ACCOUNT_BASE64 }}
