name: Deploy Dev

on:
  workflow_dispatch:

concurrency:
  group: deploy-dev
  cancel-in-progress: true

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit
    with:
      env: dev
      publish_dummy_data: true
