const {test}=require('node:test');
const assert=require('node:assert/strict');
const {withLock}=require('./lock');
function fixture(){let owner=null,sequence=0;const writes=[];return {writes,get owner(){return owner},set owner(x){owner=x},gh:async(path,method,body)=>{if(path.endsWith('/heads/main'))return {object:{sha:'a'.repeat(40)}};if(path.endsWith('/git/tags'))return {sha:'tag'+(++sequence)};if(method==='POST'){writes.push(body);if(owner)throw Object.assign(new Error('Reference already exists'),{status:422});owner=body.sha;return {}};if(method==='DELETE'){writes.push('delete '+owner);owner=null;return {}};if(!owner)throw Object.assign(new Error('not found'),{status:404});return {object:{sha:owner}}}}}
const options={attempts:4,delay:1};
test('parallel consumer and Enterprise writers both complete without overlapping',async()=>{const f=fixture();let active=0,maximum=0,finished=0;const run=()=>withLock(f.gh,'repo',async()=>{active++;maximum=Math.max(maximum,active);await new Promise(r=>setTimeout(r,2));active--;finished++}, {...options,attempts:20});await Promise.all([run(),run()]);assert.equal(maximum,1);assert.equal(finished,2);assert.equal(f.owner,null)});
test('busy holder is never stolen and timeout identifies the retry action',async()=>{const f=fixture();f.owner='other';let entered=false;await assert.rejects(withLock(f.gh,'repo',async()=>{entered=true},options),/busy.*Retry only/);assert.equal(entered,false);assert.equal(f.owner,'other');assert.ok(!f.writes.some(x=>typeof x==='string'))});
test('uncertain successful acquisition is reconciled by our unique tag',async()=>{const f=fixture();let lost=true,entered=0;const gh=async(...args)=>{const result=await f.gh(...args);if(args[0].endsWith('/git/refs')&&lost){lost=false;throw Object.assign(new Error('502'),{status:502})}return result};await withLock(gh,'repo',async()=>entered++,options);assert.equal(entered,1);assert.equal(f.owner,null)});
test('uncertain creation that did not commit retries without entering early',async()=>{const f=fixture();let first=true;const gh=async(...args)=>{if(args[0].endsWith('/git/refs')&&first){first=false;throw new TypeError('fetch failed')}return f.gh(...args)};await withLock(gh,'repo',async()=>assert.equal(f.owner,'tag1'),options);assert.equal(f.owner,null)});
test('an uncertain delete cannot delete the next holder',async()=>{const f=fixture();let first=true;const gh=async(...args)=>{const result=await f.gh(...args);if(args[1]==='DELETE'&&first){first=false;f.owner='next-holder';throw Object.assign(new Error('502'),{status:502})}return result};await withLock(gh,'repo',async()=>{},options);assert.equal(f.owner,'next-holder');assert.equal(f.writes.filter(x=>typeof x==='string').length,1)});
test('permission failure is immediate and never enters the protected operation',async()=>{const f=fixture();let waited=0,entered=false;const gh=async(...args)=>{if(args[0].endsWith('/git/refs'))throw Object.assign(new Error('403'),{status:403});return f.gh(...args)};await assert.rejects(withLock(gh,'repo',async()=>{entered=true},{...options,wait:async()=>{waited++}}),/403/);assert.equal(waited,0);assert.equal(entered,false)});
test('a failed protected operation releases its own lock',async()=>{const f=fixture(),error=new Error('Notion failed');await assert.rejects(withLock(f.gh,'repo',async()=>{throw error},options),e=>e===error);assert.equal(f.owner,null)});
