const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const { workItems, validateNote, buildManifest, withLock, record, hash, rich } = require('./record');
const { observeStore } = require('./monitor-store');
const id = 'a'.repeat(32);
const note = {kind:'feature',summary:'Export reports',audience:'Enterprise',limitations:'Cloud only',scope:'report-export-v1',targets:['web'],audienceGate:true,requiredReleaseKeys:[],workItems:[id]};
test('explicit Work Items section only; all links preserved beyond mirror caps',()=>{const ids=Array.from({length:35},(_,i)=>i.toString(16).padStart(32,'0'));assert.deepEqual(workItems('Work Items:\n'+ids.map(x=>'- https://www.notion.so/'+x).join('\n')),ids);assert.deepEqual(workItems('Mention https://www.notion.so/'+id),[])});
test('committed Work Items cannot change through mutable PR metadata',()=>{assert.throws(()=>validateNote(note,[]),/match/);assert.deepEqual(validateNote(note,[id]).workItems,[id]);assert.doesNotThrow(()=>validateNote({...note,kind:'fix',workItems:[]},[]))});
test('atomic shared ref excludes concurrent publishers and releases owner lock',async()=>{let locked=false,active=0,max=0;const gh=async(p,m,b)=>{if(p.endsWith('/heads/main'))return {object:{sha:'a'.repeat(40)}};if(p.endsWith('/git/tags'))return {sha:b.message};if(p.endsWith('/git/refs')&&m==='POST'){if(locked)throw new Error('exists');locked=b.sha;return {}};if(m==='DELETE'){locked=false;return{}};return {object:{sha:locked}}};const fn=()=>withLock(gh,'repo',async()=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,20));active--});const results=await Promise.allSettled([fn(),fn()]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(max,1);assert.equal(locked,false)});
test('exact shipped range excludes later PR; missing review prevents automatic approval',async()=>{const cwd=process.cwd();const dir=fs.mkdtempSync(path.join(os.tmpdir(),'release-ledger-'));try{process.chdir(dir);const git=(...a)=>execFileSync('git',a,{encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();git('init');git('config','user.name','Test');git('config','user.email','test@example.com');fs.writeFileSync('base','base');git('add','.');git('commit','-m','base');const base=git('rev-parse','HEAD');fs.mkdirSync('.release-notes');fs.writeFileSync('.release-notes/export.json',JSON.stringify(note));git('add','.');git('commit','-m','feature');const shipped=git('rev-parse','HEAD');fs.writeFileSync('later','later');git('add','.');git('commit','-m','later');const later=git('rev-parse','HEAD');const pr={number:7,merged_at:'2026-09-07',base:{repo:{full_name:'VeamStudios/Test'}},merge_commit_sha:shipped,head:{sha:shipped},user:{login:'author'},html_url:'https://github.com/VeamStudios/Test/pull/7',body:`Work Items:\n- https://www.notion.so/${id}\n\nRelease note: .release-notes/export.json`};let queried=[];const gh=async url=>{queried.push(url);if(url.includes('/commits/'))return [pr];if(url.includes('/reviews'))return [];if(url.includes('/files'))return [{filename:'.release-notes/export.json',status:'added'}];return pr};const config={repo:'VeamStudios/Test',target:'web',product:'Test',version:'v1',commit:shipped,event:'release',source:pr.html_url};const m=await buildManifest(config,gh,base);assert.equal(m.commit,shipped);assert.equal(m.changes.length,1);assert.equal(m.prs[0].approved,false);assert.ok(m.issues.some(x=>x.includes('human review')));assert.ok(!queried.some(x=>x.includes(later)));const gap=await buildManifest(config,gh,'');assert.equal(gap.provenanceComplete,false);assert.equal(gap.changes.length,0);
// A retry cannot regress a live observation or overwrite edited wording.
const row={id:'row',properties:{Manifest:rich(JSON.stringify(m)),Observation:rich(JSON.stringify({phase:'live',releasedAt:'2026-09-07'})),State:{select:{name:'Available'}},Changelog:rich('Edited after approval')}};const result=await record({...config,build:'',phase:'uploaded',releasesId:'releases',dryRun:true},{gh,notion:async()=>({results:[row],has_more:false})});assert.equal(result.properties.Observation,undefined);assert.equal(result.properties.Changelog,undefined);
}finally{process.chdir(cwd);fs.rmSync(dir,{recursive:true,force:true})}});
function apple(build='123',phased=null){return {findAppByBundleId:async()=>({id:'app',attributes:{bundleId:'com.test.app'}}),get:async p=>p.endsWith('/build')?{data:{attributes:{version:build}}}:p.endsWith('/appStoreVersionPhasedRelease')?{data:phased}:{data:[{id:'version',attributes:{versionString:'1.2.3',platform:'IOS',appStoreState:'READY_FOR_DISTRIBUTION'}}]}}}
test('App Store exact build mismatch fails; staged rollout remains limited',async()=>{const m={version:'v1.2.3',build:'123',commit:'a'.repeat(40)};await assert.rejects(observeStore(m,'com.test.app',apple('124')),/differs/);const full=await observeStore(m,'com.test.app',apple());assert.equal(full.phase,'live');assert.equal(full.timeBasis,'first-observed');const limited=await observeStore(m,'com.test.app',apple('123',{attributes:{phasedReleaseState:'ACTIVE'}}));assert.equal(limited.phase,'rollout')});
