name: 🔨 [TASK]
description: Add a general Issue or Task.
title: "<type>: <title>"
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: Type of Issue or Task.
      options:
        - fix
        - feat
        - build
        - chore
        - ci
        - docs
        - style
        - refac
        - perf
        - test
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: Describe what should be added / improved / changed.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Related Issues
      description: Links to PRs or Issues that are related to this task.
      placeholder: |
        Fixes #123
    validations:
      required: false

  - type: textarea
    attributes:
      label: Links
      description: Slack or Notion links that are related to this task.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Attachments
      description: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
