name: 🐞 [BUG] General
description: File a bug/issue for iOS
title: "[BUG] <title>"
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
      render: bash
    validations:
      required: false
  - type: dropdown
    id: type
    attributes:
      label: type
      description: What type of bug?
      options:
        - iOS
        - Web
        - Backend
        - Android
      default: 0
    validations:
      required: true
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you using?
      options:
        - Dev
        - Beta
        - Production
      default: 0
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: What device are you running on?
      options:
        - iPhone (Default)
        - iPad
        - Simulator iPhone
        - Simulator iPad
      default: 0
      multiple: true
    validations:
      required: true
    if: "${{ env.type == 'iOS' }}"
  - type: input
    id: osversion
    attributes:
      label: OS Version
      description: "What version of iOS/iPadOS are you running?"
      placeholder: "iOS 18.1"
    validations:
      required: true
    if: "${{ env.type == 'iOS' }}"
  - type: input
    id: appversion
    attributes:
      label: App Version
      description: "What version of the App are you running?"
      placeholder: "0.8.34"
    validations:
      required: true
    if: "${{ env.type == 'iOS' || env.type == 'Android' }}"
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: What device are you running on?
      options:
        - Mac
        - Windows
      default: 0
      multiple: true
    validations:
      required: true
    if: "${{ env.type == 'Web' }}"
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: What browser are you running on?
      options:
        - Safari
        - Chrome
        - Firefox
        - Edge
        - Opera
        - Other (please specify)
      default: 0
      multiple: true
    validations:
      required: true
    if: "${{ env.type == 'iOS' }}"
  - type: textarea
    attributes:
      label: Attachments
      description: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false