name: 🐞 [BUG] Multi-Platform
description: File a bug/issue for iOS, Android, Web, or Backend
title: "[BUG] <title>"
labels: ["bug"]
body:
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform is this bug report for?
      options:
        - iOS
        - Android
        - Web
        - Backend
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
      render: bash
    validations:
      required: false

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you using?
      options:
        - Dev
        - Beta
        - Production
      default: 0
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: App Version
      description: What version of the app are you running?
      placeholder: e.g., 1.2.3
    validations:
      required: false
      
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: What device are you running on?
      options:
        - iPhone
        - iPad
        - Android Phone
        - Android Tablet
        - Mac
        - Windows
        - Linux
        - Other (please specify)
      multiple: true
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: For Web issues, what browser are you using?
      options:
        - Safari
        - Chrome
        - Firefox
        - Edge
        - Opera
        - Other (please specify)
      multiple: true
    validations:
      required: false

  - type: input
    id: os_version
    attributes:
      label: OS Version
      description: What version of the operating system are you running?
      placeholder: e.g., iOS 15.5, Android 12, macOS 12.4, Windows 11
    validations:
      required: false

  - type: textarea
    attributes:
      label: Attachments
      description: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
