name: 🤦‍♂️ [SUPPORT] SAP Issues
description: For support tickets regarding Cloud account issues or Billing Transfer requests.
title: "[SUPPORT] "
labels: ["support"]
assignees: []
body:
  - type: input
    id: ticket-number
    attributes:
      label: Ticket number
      description: Enter the support ticket number
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: Select the type of issue
      options:
        - Cloud Account Issue
        - Billing Transfer Request
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Existing Account (To keep)"

  - type: input
    id: existing-account-id
    attributes:
      label: Account ID
    validations:
      required: true

  - type: input
    id: existing-account-rc
    attributes:
      label: RC Link
      placeholder: https://app.revenuecat.com/customers/...
    validations:
      required: true

  - type: input
    id: existing-account-email
    attributes:
      label: Email
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## New Account ('Dummy' account)"

  - type: input
    id: new-account-id
    attributes:
      label: Account ID
      description: Fill this out only for Billing Transfer Requests

  - type: input
    id: new-account-rc
    attributes:
      label: RC Link
      description: Fill this out only for Billing Transfer Requests
      placeholder: https://app.revenuecat.com/customers/...

  - type: input
    id: new-account-email
    attributes:
      label: Email
      description: Fill this out only for Billing Transfer Requests

  - type: textarea
    id: errors-notes
    attributes:
      label: Errors or points of note
      description: e.g., Billing Issue, second account created on the subscription, etc.
    validations:
      required: true

  - type: textarea
    id: action-required
    attributes:
      label: Action required
      description: Specify action needed, e.g., "Billing Transfer" for transfer requests
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If available, add screenshots of the subscription details. You can drag and drop images here.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other relevant information