name: 🐞 Bug
description: File a bug/issue
title: "[BUG] <title>"
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
      render: bash
    validations:
      required: false
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: What device are you running on?
      options:
        - iPhone (Default)
        - iPad
        - Simulator iPhone
        - Simulator iPad
      default: 0
      multiple: true
    validations:
      required: true
  - type: input
    id: osversion
    attributes:
      label: OS Version
      description: "What version of iOS/iPadOS are you running?"
      placeholder: "iOS 18.1"
    validations:
      required: true
  - type: input
    id: appversion
    attributes:
      label: App Version
      description: "What version of the App are you running?"
      placeholder: "0.8.34"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Attachments
      description: |
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false