'use strict';
const {test} = require('node:test');
const assert = require('node:assert/strict');
const h = require('./index');
const repo = 'VeamStudios/Example';
const options = {name: '@veamstudios/cip', url: 'https://github.com/VeamStudios/ChecklistInspectorPro-Models', target: '0.145.0', kind: 'npm', prefix: 'chore/update-cip-models-', base: 'main'};
const manifest = pin => JSON.stringify({dependencies: {'@veamstudios/cip': pin, other: '1.0.0'}});
const lock = (pin, other = '1.0.0') => JSON.stringify({lockfileVersion: 3, packages: {'': {dependencies: {'@veamstudios/cip': pin, other: '1.0.0'}}, 'node_modules/@veamstudios/cip': {version: pin}, 'node_modules/other': {version: other}}});
const encoded = text => ({type: 'file', encoding: 'base64', content: Buffer.from(text).toString('base64')});
const delta = (files = ['.github/workflows/check.yml', 'package.json', 'scripts/test_release_workflow.py'], message = 'ci: improve tests') => ({status: 'ahead', total_commits: 1, files: files.map(filename => ({filename})), commits: [{commit: {message}}]});
function fixture({source = delta(), collateral = false, from = '0.144.0', humanCommit = false, humanComment = false, stale = false, patchFails = false} = {}) {
  const calls = [];
  const pr = number => ({number, state: 'open', html_url: `https://github.com/${repo}/pull/${number}`, user: {login: h.BOT, type: 'Bot'},
    body: `Auto-generated by CIP-Models CI.\nUpdates Models to ${number === 2 ? '0.145.0' : '0.144.0'}.\nExisting context.`,
    base: {ref: 'main', sha: 'base'}, head: {ref: options.prefix + (number === 2 ? '0.145.0' : '0.144.0'), sha: stale && number === 2 ? 'moved' : `head${number}`, repo: {full_name: repo}}});
  async function api(method, path, body) {
    calls.push({method, path, body});
    if (method === 'PATCH') { if (patchFails && path.endsWith('/2')) throw new Error('description update failed'); return {}; }
    if (/\/contents\//.test(path)) {
      const isModels = path.includes('ChecklistInspectorPro-Models/contents');
      const before = path.endsWith('ref=base') || path.includes('ref=v0.144.0');
      if (path.includes('/package.json?')) return encoded(isModels ? JSON.stringify({name: '@veamstudios/cip', version: before ? from : '0.145.0'}) : manifest(before ? from : path.endsWith('ref=head1') ? '0.144.0' : '0.145.0'));
      if (path.includes('/package-lock.json?')) return encoded(lock(before ? from : path.endsWith('ref=head1') ? '0.144.0' : '0.145.0', collateral && !before ? '2.0.0' : '1.0.0'));
    }
    if (path.includes('/compare/')) return path.includes('v0.144.0...v0.145.0') ? source : {status: 'ahead', total_commits: 0, files: [], commits: []};
    if (/\/pulls\/\d+$/.test(path)) return pr(Number(path.match(/\d+$/)[0]));
    if (path.includes('/files?')) return [{filename: 'package.json'}, {filename: 'package-lock.json'}];
    if (path.includes('/commits?')) return [{author: {login: humanCommit ? 'developer' : h.BOT}, committer: {login: h.BOT}}];
    if (path.includes('/comments?')) return humanComment ? [{user: {type: 'User', login: 'reviewer'}}] : [];
    if (path.includes('/reviews?')) return [];
    throw new Error(`Unexpected API request ${path}`);
  }
  return {api, calls, replacement: pr(2), old: pr(1)};
}

test('only exact stable versions and known Models repositories are accepted', () => {
  assert.equal(h.compare('0.144.0', '0.145.0'), -1);
  for (const input of ['latest', '^0.145.0', '0.145.0-beta', '0.145.0;echo bad', '01.2.3']) assert.throws(() => h.version(input));
  assert.throws(() => h.packageRepo('https://example.com/Models'));
});
test('internal source delta and isolated npm lock change qualify for routine merge', async () => {
  const f = fixture(); const result = await h.assessPR(f.api, repo, f.replacement, options);
  assert.equal(result.from, '0.144.0'); assert.equal(result.safe, true);
  assert.match(h.assessmentBody(result), /once required CI passes/);
});
test('cumulative delta is from main-resolved version, even when latest commit is ci', async () => {
  const f = fixture({from: '0.140.0', source: delta(['schema/Item.yml', 'ios/Item.swift'], 'feat(schema)!: change Item')});
  // Return a feature/breaking delta for the full baseline range.
  const api = (method, path, body) => path.includes('/compare/v0.140.0...v0.145.0') ? Promise.resolve(delta(['schema/Item.yml'], 'feat(schema)!: change Item\n\nBREAKING CHANGE: field removed')) : f.api(method, path, body);
  const result = await h.assessPR(api, repo, f.replacement, options);
  assert.equal(result.safe, false); assert.equal(result.source.breaking, true); assert.equal(result.from, '0.140.0');
});
test('other npm dependency changes require review', async () => {
  const f = fixture({collateral: true}); const result = await h.assessPR(f.api, repo, f.replacement, options);
  assert.equal(result.safe, false); assert.match(result.reasons.join(' '), /Other dependency/);
});
test('incomplete source comparison never claims safe', async () => {
  const source = {...delta(), total_commits: 251}; const f = fixture({source});
  const result = await h.assessPR(f.api, repo, f.replacement, options); assert.equal(result.safe, false); assert.equal(result.coverage, false);
});
test('missing source access is a review-required unknown', async () => {
  const f = fixture(); const api = (method, path, body) => path.includes('/compare/') ? Promise.reject(new Error('no source access')) : f.api(method, path, body);
  const result = await h.assessPR(api, repo, f.replacement, options); assert.equal(result.safe, false); assert.match(result.reasons.join(' '), /incomplete/);
});
test('Yarn parser resolves the actual pin and ignores only the Models block', () => {
  const text = '"@veamstudios/cip@^0.140.0":\n  version "0.144.0"\n  resolved "url"\n\nother@1:\n  version "1.0.0"\n';
  assert.equal(h.npmSnapshot(manifest('^0.140.0'), text, 'yarn.lock', options.name).version, '0.144.0');
  assert.throws(() => h.npmSnapshot(manifest('^0.140.0'), text + '"@veamstudios/cip@0.130.0":\n  version "0.130.0"\n', 'yarn.lock', options.name));
});
test('SPM comparison ignores formatting, flags changed other pins, and scopes the project version', () => {
  const pin = (name, v) => ({identity: name, location: name === 'models' ? options.url : 'https://github.com/other/package', state: {version: v, revision: v}});
  const a = h.spmSnapshot(JSON.stringify({pins: [pin('models', '0.144.0'), pin('other', '1.0.0')]}), options.url);
  const b = h.spmSnapshot(JSON.stringify({pins: [pin('other', '2.0.0'), pin('models', '0.145.0')]}), options.url);
  assert.notDeepEqual(a.other, b.other);
  const project = v => `A /* XCRemoteSwiftPackageReference */ = {\n repositoryURL = "${options.url}";\n requirement = {\n version = ${v};\n };\n};\n`;
  assert.equal(h.projectWithoutModelsVersion(project('0.144.0'), options.url), h.projectWithoutModelsVersion(project('0.145.0'), options.url));
  assert.throws(() => h.projectWithoutModelsVersion('unrelated', options.url));
});
test('only same-repo, same-base, correctly prefixed release-bot PRs are managed', () => {
  const f = fixture(); assert.equal(h.managed(f.old, options, repo), true);
  for (const edit of [p => p.user.login = 'developer', p => p.base.ref = 'feature', p => p.head.repo.full_name = 'other/fork', p => p.head.ref = 'feature/models', p => p.body = 'Human-owned task']) {
    const pr = structuredClone(f.old); edit(pr); assert.equal(h.managed(pr, options, repo), false);
  }
});
test('description is persisted before any old PR is closed and old context is retained', async () => {
  const f = fixture(); const result = await h.finish(f.api, repo, f.replacement, [f.old], options);
  assert.equal(result.outcome.closed.length, 1);
  const writes = f.calls.filter(call => call.method === 'PATCH');
  assert.match(writes[0].path, /\/2$/); assert.match(writes[1].path, /\/1$/);
  assert.equal(writes[1].body.state, 'closed'); assert.match(writes[1].body.body, /Existing context/); assert.match(writes[1].body.body, /Superseded by/);
});
test('failed replacement description prevents cleanup', async () => {
  const f = fixture({patchFails: true}); await assert.rejects(h.finish(f.api, repo, f.replacement, [f.old], options));
  assert.equal(f.calls.some(call => call.body?.state === 'closed'), false);
});
for (const variant of [{humanCommit: true}, {humanComment: true}, {stale: true}]) test(`preserve old PR when ${Object.keys(variant)[0]}`, async () => {
  const f = fixture(variant); const assessment = {coverage: true, from: '0.144.0', head: 'head2', base: 'base'};
  if (variant.stale) await assert.rejects(h.supersede(f.api, repo, f.replacement, assessment, [f.old], options));
  else assert.equal((await h.supersede(f.api, repo, f.replacement, assessment, [f.old], options)).closed.length, 0);
  assert.equal(f.calls.some(call => call.body?.state === 'closed'), false);
});
test('unverified source coverage prevents cleanup', async () => {
  const f = fixture(); assert.equal((await h.supersede(f.api, repo, f.replacement, {coverage: false}, [f.old], options)).closed.length, 0);
  assert.equal(f.calls.length, 0);
});
test('assessment refresh preserves unrelated body and bot summaries', () => {
  const result = {safe: false, reasons: ['Review'], files: [], base: 'base', head: 'head', to: '0.145.0'};
  const initial = h.withAssessment('Human context\n<!-- CURSOR_SUMMARY -->bot summary', result);
  const refreshed = h.withAssessment(initial, {...result, reasons: ['New review']});
  assert.equal((refreshed.match(/MODELS-UPGRADE-ASSESSMENT:start/g) || []).length, 1);
  assert.match(refreshed, /Human context/); assert.match(refreshed, /bot summary/); assert.match(refreshed, /New review/);
});
test('older PR edited during assessment is preserved', async () => {
  const f = fixture(); let reads = 0;
  const api = async (method, path, body) => {
    const result = await f.api(method, path, body);
    if (method === 'GET' && path.endsWith('/pulls/1') && ++reads > 1) return {...result, body: result.body + '\nNew human context.'};
    return result;
  };
  const result = await h.supersede(api, repo, f.replacement, {coverage: true, from: '0.144.0', head: 'head2', base: 'base'}, [f.old], options);
  assert.equal(result.closed.length, 0); assert.match(result.kept.join(' '), /changed during assessment/);
});
test('full SPM assessment checks source changes and unrelated package pins', async () => {
  const f = fixture(); const spmOptions = {...options, kind: 'spm'};
  const project = v => `A /* XCRemoteSwiftPackageReference */ = {\n repositoryURL = "${options.url}";\n requirement = {\n version = ${v};\n };\n};\n`;
  const resolved = (v, other) => JSON.stringify({pins: [{identity: 'models', location: options.url, state: {version: v}}, {identity: 'other', location: 'https://example.com/other', state: {version: other}}]});
  const api = async (method, path, body) => {
    const before = path.endsWith('ref=base');
    if (path.includes('/files?')) return [{filename: 'App.xcodeproj/project.pbxproj'}, {filename: 'App.xcodeproj/xcshareddata/swiftpm/Package.resolved'}];
    if (path.includes('/contents/App.xcodeproj/project.pbxproj?')) return encoded(project(before ? '0.144.0' : '0.145.0'));
    if (path.includes('/contents/App.xcodeproj/xcshareddata/swiftpm/Package.resolved?')) return encoded(resolved(before ? '0.144.0' : '0.145.0', before ? '1.0.0' : '2.0.0'));
    return f.api(method, path, body);
  };
  const result = await h.assessPR(api, repo, f.replacement, spmOptions);
  assert.equal(result.coverage, true); assert.equal(result.safe, false); assert.match(result.reasons.join(' '), /Other SPM/);
});
