'use strict';
const {execFileSync} = require('node:child_process');
const helper = require('./index');

function git(...args) { return execFileSync('git', args, {encoding: 'utf8'}).trim(); }
async function api(method, path, body) {
  const response = await fetch(`https://api.github.com${path}`, {method, headers: {
    Authorization: `Bearer ${process.env.MODELS_GITHUB_TOKEN}`,
    Accept: 'application/vnd.github+json', 'X-GitHub-Api-Version': '2022-11-28',
    ...(body ? {'Content-Type': 'application/json'} : {}),
  }, ...(body ? {body: JSON.stringify(body)} : {})});
  if (!response.ok) { const error = new Error(`GitHub ${method} ${path.split('?')[0]} failed (${response.status})`); error.status = response.status; throw error; }
  return response.json();
}
async function run() {
  const repo = process.env.GITHUB_REPOSITORY;
  const options = {target: process.env.MODELS_VERSION, name: process.env.MODELS_PACKAGE_NAME, url: process.env.MODELS_PACKAGE_URL,
    kind: process.env.MODELS_KIND, prefix: process.env.MODELS_BRANCH_PREFIX, base: process.env.MODELS_BASE_BRANCH || 'main'};
  helper.version(options.target); helper.packageRepo(options.url);
  if (!['npm', 'spm'].includes(options.kind) || !/^chore\/update-(sap|cip)-models-$/.test(options.prefix)) throw new Error('Unsupported Models updater inputs');
  if (options.kind === 'npm' && options.name !== (options.url.includes('SiteAuditPro') ? '@veamstudios/sap' : '@veamstudios/cip')) throw new Error('Models package name/repository mismatch');
  const candidates = await helper.all(api, `/repos/${repo}/pulls?state=open&base=${encodeURIComponent(options.base)}`);
  const managed = candidates.filter(pr => helper.managed(pr, options, repo));
  if (managed.some(pr => helper.compare(helper.prVersion(pr, options), options.target) > 0)) {
    console.log('A newer managed Models upgrade already exists; ignoring the stale dispatch.'); return;
  }
  let pr = managed.filter(pr => helper.prVersion(pr, options) === options.target).sort((a, b) => b.number - a.number)[0];
  if (!pr) {
    const changed = git('diff', '--name-only');
    if (!changed) { console.log('No dependency changes; no replacement or cleanup performed.'); return; }
    // A delayed event must not create a downgrade after a newer upgrade has merged.
    const baseRef = await api('GET', `/repos/${repo}/git/ref/heads/${encodeURIComponent(options.base)}`);
    const baseline = await helper.baselineVersion(api, repo, baseRef.object.sha, changed.split('\n'), options);
    if (helper.compare(baseline, options.target) >= 0) {
      console.log('Main already resolves this or a newer Models version; no replacement or cleanup performed.'); return;
    }
    const branch = `${options.prefix}${options.target}-${process.env.GITHUB_RUN_ID}-${process.env.GITHUB_RUN_ATTEMPT || '1'}`;
    git('checkout', '-b', branch);
    git('add', '--all');
    git('commit', '-m', process.env.MODELS_COMMIT_SUBJECT || `chore: update Models to ${options.target}`);
    git('push', 'origin', branch);
    // Create a clearly unassessed PR first. Older PRs remain open if creation or assessment fails.
    pr = await api('POST', `/repos/${repo}/pulls`, {base: options.base, head: branch,
      title: process.env.MODELS_PR_TITLE || `chore: update Models to ${options.target}`,
      body: helper.withPendingAssessment(process.env.MODELS_PR_BODY || `Auto-generated by ${options.prefix.includes('sap') ? 'SAP' : 'CIP'}-Models CI.\nUpdates Models to \`${options.target}\`.`)});
  }
  pr = await api('GET', `/repos/${repo}/pulls/${pr.number}`);
  const {assessment, outcome} = await helper.finish(api, repo, pr, candidates, options);
  console.log(`Models upgrade PR: ${pr.html_url}; internal-only assessment: ${assessment.safe}; superseded: ${outcome.closed.length}`);
}
if (require.main === module) run().catch(error => { console.error(error.message); process.exitCode = 1; });
module.exports = {api, run};
